name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        submodules: 'recursive'  # Fetch Git submodules recursively

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.11

    - name: Install edgedb
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com > edgedb.sh && chmod +x ./edgedb.sh && ./edgedb.sh -y && rm edgedb.sh

    - name: Initialize edgedb project
      run: edgedb project init --non-interactive && edgedb migration create --non-interactive && edgedb migrate
      working-directory: ./genomephone-core

    - name: Install edgedb (python)
      run: pip install edgedb

    - name: Run edgedb.codegen
      run: ln -s ../src/edgeql ./edgeql && python -m edgedb.codegen --target async --file ../src/genomephone/edgedb_interface.py
      working-directory: ./genomephone-core

    - name: Install poetry
      run: pip install poetry

    - name: Build wheel
      run: poetry build

    - name: Publish wheel
      uses: actions/upload-artifact@main
      with:
        name: wheel
        path: dist/*.whl

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@master
      with:
        file: Containerfile
        context: .
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/genomephone-frontend:latest
